---
name: "DEFAULT"
path: "cw2_results"   # location to save results in
repetitions: 1    # number of times one set of parameters is run
# Experiment Parameters:
iterations: 42

params:

  exp_name: "exp_name"
  game: "dm_control/cartpole-swingup-v0"
  n_envs: 1
  n_test_envs: 5
  rollout_steps: 10
  max_episode_length: 1000
  max_entropy_coeff: 0.0

  use_gae: true
  gae_scaling: 0.95
  discount_factor: 0.99

  norm_observations: true
  norm_rewards: false
  norm_advantages: true
  clip_observations: 0.0
  clip_rewards: 0.0
  clip_advantages: 0.0

  proj_type: "kl"
  entropy_eq: false
  entropy_first: false
  scale_prec: true
  mean_bound: 0.005
  cov_bound: 0.0005
  target_entropy: 0.0
  temperature: 0.5
  entropy_schedule: false

  optimizer: "adam"
  lr: 0.00005
  optimizer_vf: "adam"
  lr_vf: 0.00075
  lr_schedule: ""

  train_steps: 100
  epochs: 20
  val_epochs: 10

  num_minibatches: 256
  entropy_penalty_coeff: 0.0
  trust_region_coeff: 1.0
  vf_coeff: 0.0

  importance_ratio_clip: 0.0
  clip_vf: 0.0
  clip_grad_norm: 0.0

  initialization: "orthogonal"
  share_weights: false
  activation: "tanh"
  policy_type: "diag"
  minimal_std: 0.00001
  init_std: 1.0
  contextual_std: false
  hidden_sizes_policy: [64,64]
  hidden_sizes_vf: [64,64]

  do_regression: false
  regression_iters: 5
  lr_reg: 0.0001
  optimizer_reg: "adam"

  cpu: true
  advanced_logging: true
  log_interval: 1
  save_interval: 0
  out_dir: "results/"
  seed: 28
  dtype: "float64"

  #fancy_gym
  #(chose between mp1_s1000/mp2_500/mp4_s250/mp5_s200/mp8_s125/mp10_s100)
  fancy_gym_env: "swingup-max_planning_4_schedule_250"

wandb:
  project: fancy_gym with trust_region_layers
  group: my_group
---
## Slurm config (optional)
#name: "SLURM"   # MUST BE "SLURM"
#
## Required
#partition: "single"
#job-name: "fancy_gym"    # this will be the experiment's name in slurm
#
#num_parallel_jobs: 120
#ntasks: 1 # for single partition
#cpus-per-task: 8
#mem-per-cpu: 900
#time: 4320
---
name: "experiment_3"

params:
  mean_bound: 0.2
  lr: 0.00007
  fancy_gym_env: "swingup-max_planning_4_schedule_250"
---