wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692093070.80675
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      - 35
      4: 3.9.17
      5: 0.15.6
      8:
      - 5
